import { JisonParser, JisonParserApi, StateType, SymbolsType, TerminalsType, ProductionsType } from '@ts-jison/parser';
/**
 * parser generated by  @ts-jison/parser-generator 0.4.1-alpha.2
 * @returns Parser implementing JisonParserApi and a Lexer implementing JisonLexerApi.
 */
type YY_ = {
    yytext: string;
    yyleng: number;
};
export declare class EbnfParser extends JisonParser implements JisonParserApi {
    $?: any;
    symbols_: SymbolsType;
    terminals_: TerminalsType;
    productions_: ProductionsType;
    table: Array<StateType>;
    defaultActions: {
        [key: number]: any;
    };
    constructor(yy?: any, lexer?: EbnfLexer);
    performAction(yytext: string, yyleng: number, yylineno: number, yy: any, yystate: number, $$: any, _$: any): any;
}
import { JisonLexer, JisonLexerApi } from '@ts-jison/lexer';
export declare class EbnfLexer extends JisonLexer implements JisonLexerApi {
    options: any;
    constructor(yy?: any);
    rules: RegExp[];
    conditions: any;
    performAction(yy: any, yy_: YY_, $avoiding_name_collisions: any, YY_START: any): any;
}
export {};
//# sourceMappingURL=ebnf-parser.d.ts.map